### PR TITLE
Play all music in the music sound category.

### PR DESCRIPTION
**Pull request by Selim042**

### CODE REVIEW

**Comment by mibby** [comment]
@koca2000 Any update on getting this merged?

**Comment by koca2000** [comment]
@mibby I want to test it. Today I will have time to look at it.

**Comment by koca2000** [comment]
@mibby @Selim042 Sorry, but I will not merge this. Many players have music muted in settings and this api is not only for music players.

But I have to say that it is good idea. I can add possibility for developers to change `SoundCategory` with default value `MASTER`. Do you agree?

**Comment by Selim042** [comment]
What about an optional SoundCategory parameter when declaring a new SoundPlayer for it to play on?

**Comment by koca2000** [comment]
Exactly what I mean! And also `changeCategory` function.

**Comment by Selim042** [comment]
Sounds good to me.  Would you prefer I would take care of it, or are you going to take care of it?

**Comment by koca2000** [comment]
If you want to do it as it was your idea, you can. Otherwise I will do it.

**Comment by Selim042** [comment]
Done.

**Comment by Selim042** [comment]
Thank you!

**Pull request merged**
