### PR TITLE
Support sounds outside 2 octave range using resource pack

### LINKED ISSUE #47: [Feature request] Support sounds outside 2 octave range using resource pack
Support these sounds outside 2 octave range using SongPlayer#setEnable10Octave(boolean)
If set to true, enable these sounds. 
If set to false, transpose these sounds.

### PR DESCRIPTION
**Pull request by ishland**
Support sounds outside 2 octave range using resource pack

Resolves #47 

- [x] Transpose notes

- [x] Support notes outside range

- [x] Add toggle selection

### CODE REVIEW

**Comment by koca2000** [comment]
Hi! Thank you for your PR. I need to make sure everything is ok and it won't break anything (eg. backward compatibility). It will take same time.

**Comment by FluxCapacitor2** [comment]
Any update on this? I tested on my own server and ishland's branch worked as a drop-in replacement for the current version. (Haven't tested transposing notes that are out of range)

**Comment by koca2000** [comment]
Hi @ishland! I am trying to realise how your code works. However, the part with pitch calculations seems to be wrong to me or I don't understand what you want to do.

First of all, pitch in Minecraft is basically speed of playback of the instrument. Whereas 1200 NoteBlockStudio pitch is one octave so you can't just append it to the result. Also final pitch is calculated from combination of key and NBS pitch so you can't decide the octave only based on key.

I can make some comments to the code but I think that big part of it should be made differently. Especially the part around pitch calculation. The idea with +1/-1 file names is nice though.

There is something I think you missed. Minecraft is still able to play only two octaves. You have sound that is already shifted by two octaves but the pitch you send to client still have to be in those original two octaves. This means that you basically always need to transpose it and you just change the name of the instrument based on target octave. This thought can simplify the code a lot and the changes to the API are not as big when you realise it.

Maybe I am the one who is missing something. If so, let me know but right now the code is not ready to be merged.

**Comment by ishland** [comment]
First of all, base pitch calculation is correct. But adding pitch just right after it is incorrect. I will restore the original pitch calculation and see if that works. 
You misunderstood what is "transpose". OpenNoteBlockStudio definition of "transpose" is shifting note keys by 12 to the Minecraft 2 octave range and keep doing this until the note is inside 2 octave range. If we need more octave, we need to shift the key into the correct octave to produce the correct octave. Minecraft can only play 2 octaves so we need to shift our target octave to Minecraft base octave. Since our resourcepack already shifted the sound by 2 octaves, we just need to play these sounds and they will fall in the correct octave.

**Comment by koca2000** [comment]
Well, that is basically what I said. You shift it by 12 if you want to traspose it or shift it by 24 if you want to play already shifted instrument from resource pack. So you can use exactly same code and just decide how big will be your shift step and change the instrument if needed. Of course the shift has to be done after adding NBS pitch to the key as it can change octave.

**Comment by ishland** [comment]
If everything goes well, the shift after adding pitch is not needed. As the NBS is strictly encoded by OpenNoteBlockStudio, the pitch will not be higher than 2399 OpenNoteBlockStudio pitch.

**Comment by koca2000** [comment]
Pitch in OpenNoteBlockStudio can be +-1200. If you use key 58 which is outside the Minecraft octave range, shift (transpose) it to key 46 than add pitch 1200, you are back at key 58 which is outside the Minecraft octave range. You have to apply pitch first.

**Comment by ishland** [comment]
Alright, got it.

**Comment by ishland** [comment]
Some of my songs are requesting 8 octave range due to applying pitch to key. I think I need to fix that

**Comment by koca2000** [comment]
Well, we can support 10 octave range instead of 6. The code can be easily extended if you change the way you decide which instrument should be used.

**Comment by ishland** [comment]
After some testing, this PR will be ready for review

**Comment by ishland** [comment]
Minecraft is poor at handling very short sounds, I will add tiny empty space at the front of them

**Comment by ishland** [comment]
It seems like that I have messed up _2 sounds

**Comment by koca2000** [comment]
I haven't found any issues. Just one little detail. As this feature requires resource pack to work properly, it should be disabled by default.

**Pull request merged**
